"""
Django settings for shop_online project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-eco*a&uupw=-%u)2yaujek%y8yze@*&xo+5&bxy^a&toy^7ecj'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Enables debug mode; should be False in production

ALLOWED_HOSTS = []   # List of allowed hosts/domain names


# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store.apps.StoreConfig', # manual add app store
    'django_extensions',  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shop_online.urls'  # Root URL configuration for the project

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',   # Template engine backend
        'DIRS': [
            BASE_DIR / 'templates',  # Path to global templates directory
        ],
        'APP_DIRS': True,  # Enables template loading from app directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.cart_item_count',
            ],
        },
    },
]



WSGI_APPLICATION = 'shop_online.wsgi.application'  # Entry point for WSGI-compatible web servers


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Using SQLite as database backend
        'NAME': BASE_DIR / 'db.sqlite3',  # Path to database file
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', # Prevents similar passwords
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # Enforces a minimum password length
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  # Prevents common passwords
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  # Prevents purely numeric passwords
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'  # Language used for translations

TIME_ZONE = 'Europe/Bucharest'  # Time zone for the project

USE_I18N = True    # Enables Django's translation system

USE_TZ = True      # Enables timezone-aware datetimes


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # Default auto-generated primary key type


# shop_online/settings.py

LOGIN_REDIRECT_URL = '/'    # Redirect to home after successful login
LOGOUT_REDIRECT_URL = '/'   # Redirect to home after logout

APPEND_SLASH = True         # Automatically appends slash to URLs


# Importing os for path manipulations
import os


DEBUG = True  # Ensures debug mode is active (use False in production)

STATIC_URL = '/static/'  # URL prefix for static files

STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Folder where static files are stored (for development)
]

STATIC_ROOT = BASE_DIR / 'staticfiles'  # Directory for static files (for production)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # Directory for uploaded media files (e.g. product images)


SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Session backend using database



CSRF_COOKIE_HTTPONLY = True  # Makes CSRF cookie inaccessible to JavaScript
CSRF_COOKIE_SECURE = False   # Set to True if using HTTPS
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 'http://127.0.0.1:8000/store/signup/']  # Trusted domains for CSRF validation




LOGOUT_REDIRECT_URL = 'store:home'  # Redirect to store home after logout

CSRF_COOKIE_SECURE = False          # Duplicate setting — make sure to keep only one in practice
 
# Autodisconnect if user/admin does nothing on website for 1 minute
SESSION_COOKIE_AGE = 3600  # 60 minutes (1800 seconds = 30 minutes) session expiration time
# This line means : sesion expire when browser close
SESSION_EXPIRE_AT_BROWSER_CLOSE = True




from dotenv import load_dotenv # Load environment variables from .env file
load_dotenv()  # Load variables from .env

WEATHER_API_KEY = os.getenv('WEATHER_API_KEY')  # Obține cheia API

# Send Contact Message directly to ADMINs email address:  SMTP 
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # for local development
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"  # Folosim backend-ul SMTP standard
# EMAIL_HOST = 'smtp.sendgrid.net'  # Server-ul SMTP al SendGrid
# EMAIL_PORT = 587  # Portul 587 pentru TLS
# EMAIL_USE_TLS = True  # Activăm TLS
# EMAIL_HOST_USER = 'apikey'  # Userul este "apikey" pentru SendGrid
# EMAIL_HOST_PASSWORD = os.getenv('SENDGRID_API_KEY')  # Cheia ta API SendGrid
# DEFAULT_FROM_EMAIL = 'iuliansami@gmail.com'  # Adresa de expeditor




# Send Contact Message directly to ADMINs email address:  API KEY
# Sendgrid key for sending emails
SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")

# Optional settings for SendGrid
DEFAULT_FROM_EMAIL = "iuliansami@gmail.com"