# Generated by Django 4.1.1 on 2025-04-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_is_ordered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
