# Generated by Django 4.1.1 on 2025-04-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_profile_avatar_profile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_communication',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zip_code',
        ),
    ]
